version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: daily
      time: "02:00"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: daily
      time: "02:00"
    open-pull-requests-limit: 10
