name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Run Tests
        run: |
          yarn test:ci

      - name: Collect Coverage
        if: "!contains(github.event.pull_request.labels.*.name, 'dependencies')"
        run: |
          yarn coverage

      - name: Upload Coverage Reports to Codecov
        if: "!contains(github.event.pull_request.labels.*.name, 'dependencies')"
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
